# Generated by Django 3.0.6 on 2020-05-10 15:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='邮箱')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('comment_content', models.TextField(verbose_name='评论内容')),
                ('is_examine', models.BooleanField(default=False, verbose_name='是否审核通过')),
                ('post_comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment', to='post.Post')),
            ],
        ),
    ]
